nsl_kdd:
  path: "data/raw/nsl_kdd/KDDTest+.arff"

cicids2017:
  path: "data/raw/cicids2017/"
  files:
    - "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
    - "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv"
    - "Friday-WorkingHours-Morning.pcap_ISCX.csv"
    - "Monday-WorkingHours.pcap_ISCX.csv"
    - "Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv"
    - "Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv"
    - "Tuesday-WorkingHours.pcap_ISCX.csv"
    - "Wednesday-workingHours.pcap_ISCX.csv"