isolation_forest_params:
  contamination: 0.1
  random_state: 42

autoencoder_params:
  input_dim: 41  # Adjust based on the number of features after unification
  encoding_dim: 20
  epochs: 50
  batch_size: 32

real_time:
  buffer_size: 100